name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 UTC
  workflow_dispatch:

concurrency:
  group: github-profile-stats
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub Statistics
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/userstats.svg
          include-title: true
          colors: light
          fail-on-error: true
          commit-and-push: true
          locale: en
          border-radius: 6
          show-border: true
          small-title: false
          max-languages: auto
          category-order: general, repositories, contributions, languages
          animated-language-chart: false
          language-animation-speed: 10
          image-width: 0
          top-icon: default
          commit-message: "Update GitHub statistics"
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_TOKEN }}
